serviceAccount:
  create: false
  name: ""

erpnext:
  replicaCount: 1
  image:
    repository: frappe/erpnext
    tag: v15.75.1
    pullPolicy: IfNotPresent

gunicorn:
  enabled: true
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8000

scheduler:
  enabled: false

worker:
  enabled: false

socketio:
  enabled: false

nginx:
  enabled: false
