# ERPNext Helm Chart Values (clean + persistent, no Bitnami, no IAM)

# Global ERPNext image
image:
  repository: frappe/erpnext
  tag: "14.30.5"
  pullPolicy: IfNotPresent

# Gunicorn (backend app server)
gunicorn:
  replicaCount: 1
  image:
    repository: frappe/erpnext-worker
    tag: "14.30.5"
  service:
    type: ClusterIP
    port: 8000

# Workers (default, short, long)
worker:
  default:
    replicaCount: 1
    image:
      repository: frappe/erpnext-worker
      tag: "14.30.5"
  short:
    replicaCount: 1
    image:
      repository: frappe/erpnext-worker
      tag: "14.30.5"
  long:
    replicaCount: 1
    image:
      repository: frappe/erpnext-worker
      tag: "14.30.5"

# Scheduler
scheduler:
  replicaCount: 1
  image:
    repository: frappe/erpnext-worker
    tag: "14.30.5"

# SocketIO
socketio:
  replicaCount: 1
  image:
    repository: frappe/erpnext-worker
    tag: "14.30.5"
  service:
    type: ClusterIP
    port: 9000

# Nginx
nginx:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx
    tag: "1.25"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080

# MariaDB (instead of Postgres)
mariadb:
  enabled: true
  image:
    repository: mariadb
    tag: "10.11"
  auth:
    rootPassword: root
    username: frappe
    password: frappe
    database: erpnext
  primary:
    persistence:
      enabled: true
      storageClass: standard   # <-- change to your storageClass (longhorn, efs, etc.)
      accessModes: ["ReadWriteOnce"]
      size: 10Gi
    service:
      port: 3306

# Redis
redis:
  enabled: true
  image:
    repository: redis
    tag: "7"
  master:
    persistence:
      enabled: true
      storageClass: standard   # <-- change to your storageClass
      accessModes: ["ReadWriteOnce"]
      size: 2Gi
  service:
    port: 6379

# ERPNext volumes (sites + logs)
persistence:
  sites:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: standard   # <-- change this
  logs:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClass: standard   # <-- change this
