# ERPNext Helm Chart Values (clean + working, no Bitnami, no IAM)

# Global ERPNext image
image:
  repository: frappe/erpnext
  tag: "14.30.5"
  pullPolicy: IfNotPresent

# Gunicorn (backend app server)
gunicorn:
  replicaCount: 1
  image:
    repository: frappe/erpnext-worker
    tag: "14.30.5"
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

# Workers (default, short, long)
worker:
  default:
    replicaCount: 1
    image:
      repository: frappe/erpnext-worker
      tag: "14.30.5"
    resources:
      requests:
        cpu: "300m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

  short:
    replicaCount: 1
    image:
      repository: frappe/erpnext-worker
      tag: "14.30.5"
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"

  long:
    replicaCount: 1
    image:
      repository: frappe/erpnext-worker
      tag: "14.30.5"
    resources:
      requests:
        cpu: "300m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

# Scheduler
scheduler:
  replicaCount: 1
  image:
    repository: frappe/erpnext-worker
    tag: "14.30.5"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

# SocketIO
socketio:
  replicaCount: 1
  image:
    repository: frappe/erpnext-worker
    tag: "14.30.5"
  service:
    type: ClusterIP
    port: 9000
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"

# Nginx
nginx:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx
    tag: "1.25"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

# MariaDB (instead of Postgres)
mariadb:
  enabled: true
  image:
    repository: mariadb
    tag: "10.11"
  auth:
    rootPassword: root
    username: frappe
    password: frappe
    database: erpnext
  primary:
    service:
      port: 3306
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# Redis
redis:
  enabled: true
  image:
    repository: redis
    tag: "7"
  service:
    port: 6379
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "300m"
      memory: "512Mi"
