image:
  repository: frappe/erpnext
  tag: version-14
  pullPolicy: IfNotPresent

replicaCount: 1

gunicorn:
  service:
    type: ClusterIP
    port: 8000

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  logsSize: 1Gi

siteConfig:
  dbHost: mariadb
  dbRootPassword: admin
  dbName: erpnext
  dbUser: erpnext
  dbPassword: erpnext
  adminPassword: admin
  siteName: site1.local
