# =========================================================
# ERPNext Helm Chart Values (clean + working + persistent)
# Compatible with official frappe/helm chart
# =========================================================

# Global ERPNext image
image:
  repository: frappe/erpnext
  tag: "14.30.5"
  pullPolicy: IfNotPresent

# Service Account (disable to avoid IAM bindings)
serviceAccount:
  create: false
  name: ""

# Gunicorn (backend app server)
gunicorn:
  replicaCount: 1
  image:
    repository: frappe/erpnext-worker
    tag: "14.30.5"
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

# Workers (default, short, long)
worker:
  default:
    replicaCount: 1
    image:
      repository: frappe/erpnext-worker
      tag: "14.30.5"
  short:
    replicaCount: 1
    image:
      repository: frappe/erpnext-worker
      tag: "14.30.5"
  long:
    replicaCount: 1
    image:
      repository: frappe/erpnext-worker
      tag: "14.30.5"

# Scheduler
scheduler:
  replicaCount: 1
  image:
    repository: frappe/erpnext-worker
    tag: "14.30.5"

# SocketIO (for real-time updates)
socketio:
  replicaCount: 1
  image:
    repository: frappe/erpnext-worker
    tag: "14.30.5"
  service:
    type: ClusterIP
    port: 9000

# Nginx (frontend reverse proxy)
nginx:
  enabled: true
  replicaCount: 1
  image:
    repository: nginx
    tag: "1.25"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080

# MariaDB (required by ERPNext, Postgres not supported)
mariadb:
  enabled: true
  image:
    repository: mariadb
    tag: "10.11"
  auth:
    rootPassword: root
    username: frappe
    password: frappe
    database: erpnext
  primary:
    persistence:
      enabled: true
      storageClass: standard     # <-- CHANGE to your cluster's storageClass
      accessModes: ["ReadWriteOnce"]
      size: 10Gi
    service:
      port: 3306

# Redis (for caching + queues)
redis:
  enabled: true
  image:
    repository: redis
    tag: "7"
  master:
    persistence:
      enabled: true
      storageClass: standard     # <-- CHANGE
      accessModes: ["ReadWriteOnce"]
      size: 2Gi
  service:
    port: 6379

# ERPNext persistence (sites + logs)
persistence:
  sites:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: standard      # <-- CHANGE
  logs:
    enabled: true
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClass: standard      # <-- CHANGE

# Disable optional jobs (for simplicity)
jobs:
  createSite:
    enabled: false
  backup:
    enabled: false
  migrate:
    enabled: false
  restore:
    enabled: false
  dropSite:
    enabled: false

# Disable ingress by default (use your own ingress controller later)
ingress:
  enabled: false

# No autoscaling
autoscaling:
  enabled: false
