image:
  repository: frappe/erpnext
  tag: version-14
  pullPolicy: IfNotPresent

replicaCount: 1

gunicorn:
  enabled: true
  service:
    type: ClusterIP
    port: 8000

nginx:
  enabled: false
  service:
    type: ClusterIP
    port: 8080

socketio:
  enabled: false
  service:
    type: ClusterIP
    port: 9000

scheduler:
  enabled: false

worker:
  enabled: false

persistence:
  enabled: false
  gunicorn:
    enabled: false
  logs:
    enabled: false
  worker:
    enabled: false
  socketio:
    enabled: false
  nginx:
    enabled: false

jobs:
  createSite:
    enabled: true
    image:
      repository: frappe/erpnext-worker
      tag: version-14
  migrate:
    enabled: true
    image:
      repository: frappe/erpnext-worker
      tag: version-14

serviceAccount:
  create: true
  name: "erpnext-sa"

siteConfig:
  dbHost: mariadb
  dbRootPassword: admin
  dbName: erpnext
  dbUser: erpnext
  dbPassword: erpnext
  adminPassword: admin
  siteName: site1.local

# --- Disable persistence in dependencies ---
mariadb:
  primary:
    persistence:
      enabled: false
      storageClass: ""

postgresql:
  primary:
    persistence:
      enabled: false
      storageClass: ""

redis:
  master:
    persistence:
      enabled: false
      storageClass: ""
  replica:
    persistence:
      enabled: false
      storageClass: ""
