image:
  repository: frappe/erpnext
  tag: version-14
  pullPolicy: IfNotPresent

replicaCount: 1

gunicorn:
  enabled: true
  service:
    type: ClusterIP
    port: 8000

nginx:
  enabled: false
  service:
    type: ClusterIP
    port: 8080

socketio:
  enabled: false
  service:
    type: ClusterIP
    port: 9000

scheduler:
  enabled: false

worker:
  enabled: false

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  logsSize: 1Gi
  gunicorn:
    enabled: true
  worker:
    enabled: false
  socketio:
    enabled: false
  nginx:
    enabled: false
  logs:
    enabled: true
    storageClass: ""    # fixed

siteConfig:
  dbHost: mariadb
  dbRootPassword: admin
  dbName: erpnext
  dbUser: erpnext
  dbPassword: erpnext
  adminPassword: admin
  siteName: site1.local
