apiVersion: v1
kind: Service
metadata:
  name: {{ include "erpnext.fullname" . }}-gunicorn
spec:
  type: {{ .Values.gunicorn.service.type }}
  selector:
    app: {{ include "erpnext.name" . }}
    tier: gunicorn
  ports:
    - protocol: TCP
      port: {{ .Values.gunicorn.service.port }}
      targetPort: 8000
